[pytest]
markers =
    jenkins: Tests for Jenkins CI/CD service
    nexus: Tests for Nexus artifact repository
    gitlab: Tests for GitLab version control and CI/CD platform
    gitlab_runner: Tests for GitLab Runner deployment and functionality
