[all]
controlplane-1 ansible_host=X.X.X.X
controlplane-2 ansible_host=X.X.X.X
controlplane-3 ansible_host=X.X.X.X
worker-1       ansible_host=X.X.X.X
worker-2       ansible_host=X.X.X.X
worker-3       ansible_host=X.X.X.X

[rke2_manager]
worker-1

[all:vars]
K8S_AUTH_KUBECONFIG=/home/your_user/.kube/config
ansible_user=your_user
ansible_password="{{ secret_ansible_password }}"
ansible_become_password="{{ secret_ansible_become_password }}"
ansible_shell_type=sh
ansible_python_interpreter=/usr/bin/python3
